export const RELEVANT_EVENTS = new Set([
  "INITIAL_PURCHASE",
  "RENEWAL",
  "PRODUCT_CHANGE",
  "NON_RENEWING_PURCHASE",
  "UNCANCELLATION",
  "SUBSCRIPTION_EXTENDED",
  "TEMPORARY_ENTITLEMENT_GRANT",
  "SUBSCRIPTION_PAUSED",
  "BILLING_ISSUE",
  "CANCELLATION",
  "EXPIRATION",
]);
