import {
  BillingModel,
  BillingPlan,
  RecurringInterval,
  BillingDiscountType,
  SubscriptionStatus,
  MobileStore,
  BillingType,
} from "../types";
import { FEATURES } from "./features";
import { billingConfigSchema } from "./schema";

import type { BillingConfig } from "./schema";

export const config = billingConfigSchema.parse({
  plans: [
    {
      id: BillingPlan.FREE,
      name: "plan.free.name",
      description: "plan.free.description",
      features: Object.values(FEATURES[BillingPlan.FREE]),
      variants: [
        {
          id: "free-onetime-flat",
          cost: 0,
          type: BillingType.FLAT,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "free-recurring-flat-day",
          cost: 0,
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
        },
        {
          id: "free-recurring-flat-week",
          cost: 0,
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
        },
        {
          id: "free-recurring-flat-month",
          cost: 0,
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
        },
        {
          id: "free-recurring-flat-year",
          cost: 0,
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
        },
        {
          id: "free-onetime-per-seat",
          cost: 0,
          type: BillingType.PER_SEAT,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "free-recurring-per-seat-day",
          cost: 0,
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
        },
        {
          id: "free-recurring-per-seat-week",
          cost: 0,
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
        },
        {
          id: "free-recurring-per-seat-month",
          cost: 0,
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
        },
        {
          id: "free-recurring-per-seat-year",
          cost: 0,
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
        },
      ],
    },
    {
      id: BillingPlan.PREMIUM,
      name: "plan.premium.name",
      description: "plan.premium.description",
      badge: "plan.premium.badge",
      features: Object.values(FEATURES[BillingPlan.PREMIUM]),
      variants: [
        /* WEB */
        {
          id: "price_1SnNokF6GIkBZmgVxQiOXZwS",
          cost: 19_900,
          type: BillingType.FLAT,
          model: BillingModel.ONE_TIME,
        },
        {
          id: "price_1TTPEkF6GIkBZmgVHZlDmRLg",
          cost: 99,
          type: BillingType.FLAT,
          interval: RecurringInterval.DAY,
          model: BillingModel.RECURRING,
        },
        {
          id: "price_1TTPF1F6GIkBZmgVEiWETNNg",
          cost: 599,
          type: BillingType.FLAT,
          interval: RecurringInterval.WEEK,
          model: BillingModel.RECURRING,
        },
        {
          id: "price_1SnNneF6GIkBZmgVdX4GP7O8",
          cost: 1_900,
          type: BillingType.FLAT,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
          model: BillingModel.RECURRING,
        },
        {
          id: "price_1SnNoVF6GIkBZmgViiuMqIv0",
          cost: 8_900,
          type: BillingType.FLAT,
          interval: RecurringInterval.YEAR,
          trialDays: 14,
          model: BillingModel.RECURRING,
        },
        {
          id: "price_1TUNa4F6GIkBZmgVwr2FWbeV",
          type: BillingType.PER_SEAT,
          model: BillingModel.ONE_TIME,
          cost: 22_000,
        },
        {
          id: "price_1TUNPLF6GIkBZmgVtDvCs2yM",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
          tiers: [
            { cost: 20, upTo: 2_000 },
            { cost: 15, upTo: 12_000 },
            { cost: 10 },
          ],
        },
        {
          id: "price_1TTPRpF6GIkBZmgV6lG07SVD",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
          tiers: [{ cost: 99, upTo: 5 }, { cost: 79, upTo: 20 }, { cost: 59 }],
        },
        {
          id: "price_1TUNOMF6GIkBZmgVmzTCvhRl",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
          tiers: [
            { cost: 12, upTo: 15_000 },
            { cost: 9, upTo: 90_000 },
            { cost: 6 },
          ],
        },
        {
          id: "price_1TTPShF6GIkBZmgVivP4R7kH",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
          tiers: [
            { cost: 579, upTo: 5 },
            { cost: 479, upTo: 20 },
            { cost: 379 },
          ],
        },
        {
          id: "price_1TUNL1F6GIkBZmgVNvs8b932",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
          tiers: [
            { cost: 8, upTo: 25_000 },
            { cost: 6, upTo: 125_000 },
            { cost: 4 },
          ],
        },
        {
          id: "price_1TTPTSF6GIkBZmgVIv8rk8pO",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
          tiers: [
            { cost: 2_000, upTo: 5 },
            { cost: 1_700, upTo: 25 },
            { cost: 1_300 },
          ],
        },
        {
          id: "price_1TUNNDF6GIkBZmgVdceUjj9h",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          trialDays: 14,
          tiers: [
            { cost: 4, upTo: 300_000 },
            { cost: 3, upTo: 1_500_000 },
            { cost: 2 },
          ],
        },
        {
          id: "price_1TTPUWF6GIkBZmgVS9Hcmt2M",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          trialDays: 14,
          tiers: [
            { cost: 19_900, upTo: 5 },
            { cost: 15_900, upTo: 25 },
            { cost: 11_900 },
          ],
        },

        /* MOBILE */
        {
          id: "core_premium_one_time_flat",
          cost: 19_900,
          type: BillingType.FLAT,
          model: BillingModel.ONE_TIME,
          hidden: true,
        },
        {
          id: "core_premium_recurring_month_flat",
          cost: 1_900,
          type: BillingType.FLAT,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
          model: BillingModel.RECURRING,
          hidden: true,
        },
        {
          id: "core_premium_recurring_year_flat",
          cost: 8_900,
          type: BillingType.FLAT,
          interval: RecurringInterval.YEAR,
          trialDays: 14,
          model: BillingModel.RECURRING,
          hidden: true,
        },
      ],
    },
    {
      id: BillingPlan.ENTERPRISE,
      name: "plan.enterprise.name",
      description: "plan.enterprise.description",
      features: Object.values(FEATURES[BillingPlan.ENTERPRISE]),
      variants: [
        {
          id: "enterprise-onetime-flat",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.FLAT,
          model: BillingModel.ONE_TIME,
          custom: true,
        },
        {
          id: "enterprise-recurring-flat-day",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
          custom: true,
        },
        {
          id: "enterprise-recurring-flat-week",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
          custom: true,
        },
        {
          id: "enterprise-recurring-flat-month",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          custom: true,
        },
        {
          id: "enterprise-recurring-flat-year",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.FLAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          custom: true,
        },
        {
          id: "enterprise-onetime-per-seat",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.PER_SEAT,
          model: BillingModel.ONE_TIME,
          custom: true,
        },
        {
          id: "enterprise-recurring-per-seat-day",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
          custom: true,
        },
        {
          id: "enterprise-recurring-per-seat-week",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
          custom: true,
        },
        {
          id: "enterprise-recurring-per-seat-month",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          custom: true,
        },
        {
          id: "enterprise-recurring-per-seat-year",
          label: "common:contactUs",
          href: "/contact",
          type: BillingType.PER_SEAT,
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          custom: true,
        },
        {
          id: "price_1TUNREF6GIkBZmgVAdvTSQFW",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.DAY,
          tiers: [
            { cost: 30, upTo: 2_000 },
            { cost: 24, upTo: 12_000 },
            { cost: 18 },
          ],
        },
        {
          id: "price_1TUNUuF6GIkBZmgVkctT17gb",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.WEEK,
          tiers: [
            { cost: 20, upTo: 15_000 },
            { cost: 15, upTo: 90_000 },
            { cost: 11 },
          ],
        },
        {
          id: "price_1TUNVbF6GIkBZmgVWfB13mOf",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.MONTH,
          trialDays: 7,
          tiers: [
            { cost: 14, upTo: 25_000 },
            { cost: 10, upTo: 125_000 },
            { cost: 7 },
          ],
        },
        {
          id: "price_1TUNWKF6GIkBZmgVuWfsC5vV",
          meterId: "mtr_test_61UdlHxtAk8SUiZEz41F6GIkBZmgV95M",
          type: BillingType.METERED,
          unit: "credit",
          model: BillingModel.RECURRING,
          interval: RecurringInterval.YEAR,
          trialDays: 14,
          tiers: [
            { cost: 6, upTo: 300_000 },
            { cost: 5, upTo: 1_500_000 },
            { cost: 3 },
          ],
        },
      ],
    },
  ],
  discounts: [
    {
      code: "50OFF",
      type: BillingDiscountType.PERCENT,
      off: 50,
      appliesTo: [
        "price_1SnNokF6GIkBZmgVxQiOXZwS",
        "price_1TTPEkF6GIkBZmgVHZlDmRLg",
        "price_1TTPF1F6GIkBZmgVEiWETNNg",
        "price_1SnNneF6GIkBZmgVdX4GP7O8",
        "price_1SnNoVF6GIkBZmgViiuMqIv0",
        "price_1TUNa4F6GIkBZmgVwr2FWbeV",
        "price_1TUNPLF6GIkBZmgVtDvCs2yM",
        "price_1TTPRpF6GIkBZmgV6lG07SVD",
        "price_1TUNOMF6GIkBZmgVmzTCvhRl",
        "price_1TTPShF6GIkBZmgVivP4R7kH",
        "price_1TUNL1F6GIkBZmgVNvs8b932",
        "price_1TTPTSF6GIkBZmgVIv8rk8pO",
        "price_1TUNNDF6GIkBZmgVdceUjj9h",
        "price_1TTPUWF6GIkBZmgVS9Hcmt2M",

        "core_premium_one_time_flat",
        "core_premium_recurring_month_flat",
        "core_premium_recurring_year_flat",

        "price_1TUNREF6GIkBZmgVAdvTSQFW",
        "price_1TUNUuF6GIkBZmgVkctT17gb",
        "price_1TUNVbF6GIkBZmgVWfB13mOf",
        "price_1TUNWKF6GIkBZmgVuWfsC5vV",
      ],
    },
  ],
}) satisfies BillingConfig;

export * from "./features";
export * from "./schema";

export const ACTIVE_SUBSCRIPTION_STATUSES = [
  SubscriptionStatus.ACTIVE,
  SubscriptionStatus.TRIALING,
];

export const MOBILE_STORE_LINKS = {
  [MobileStore.APP_STORE]: "https://apps.apple.com/account/subscriptions",
  [MobileStore.PLAY_STORE]:
    "https://play.google.com/store/account/subscriptions",
} as const satisfies Record<MobileStore, string>;
