name: CI / Publish extension

on:
  workflow_dispatch:

jobs:
  tests:
    name: 🧪 Tests
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  publish:
    name: 🚀 Publish extension
    runs-on: ubuntu-latest
    environment: Production
    needs: [tests]
    env:
      VITE_PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
      VITE_DEFAULT_LOCALE: ${{ secrets.DEFAULT_LOCALE }}
      VITE_SITE_URL: ${{ secrets.SITE_URL }}
      VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
      VITE_GOOGLE_ANALYTICS_SECRET: ${{ secrets.GOOGLE_ANALYTICS_SECRET }}
      VITE_POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
      VITE_POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
      VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      VITE_SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v6

      - name: 🔨 Setup
        uses: ./tooling/github/setup
        with:
          node-version: 20

      - name: 📦 Build
        run: pnpm turbo build --filter=extension

      - name: 🗃️ Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: extension-${{ github.sha }}
          path: apps/extension/build/*.zip

      - name: 💨 Publish!
        run: |
          npx wxt submit \
            --chrome-zip apps/extension/build/*-chrome.zip  \
            --firefox-zip apps/extension/build/*-firefox.zip --firefox-sources-zip apps/extension/build/*-sources.zip \
            --edge-zip apps/extension/build/*-chrome.zip
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_API_KEY: ${{ secrets.EDGE_API_KEY }}
